address: "東京都千代田区丸の内4丁目5-6"
ceo_name_en: "TARO YAMADA"
ceo_name_jp: "山田 太郎"
ceo_position: "CEO"
coo_name_jp: "田中 次郎"
coo_position: "COO"
cfo_name_jp: "鈴木 花子"
cfo_position: "CFO"
corporate_name: "Test Inc."
