import os

from jinja2 import Environment, FileSystemLoader, Template


class TemplateGenerator:
    def __init__(self, search_path: str, template_name: str, output_path: str):
        self.search_path = search_path
        self.template_name = template_name
        self.output_path = output_path

    def _load(self) -> Template:
        env = Environment(loader=FileSystemLoader(self.search_path, encoding="utf8"))
        tmpl = env.get_template(self.template_name)
        return tmpl

    def _render(self, template: Template) -> str:
        rendered = template.render()
        return rendered

    def _save(self, rendered: str):
        current_dir = os.getcwd()
        current_path = __file__
        this_filepath = current_path.replace(f"{current_dir}/", "")
        rendered = f"<!-- Generated by {this_filepath} -->\n" + rendered
        with open(self.output_path, "w") as f:
            f.write(rendered)

    def generate(self):
        tmpl = self._load()
        rendered = self._render(tmpl)
        self._save(rendered)


def main():
    g = TemplateGenerator(
        search_path="./dist/templates",
        template_name="layout.html",
        output_path="./dist/index.html",
    )
    g.generate()


if __name__ == "__main__":
    main()
